apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: vtpm-demo
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: mak3r
          sudo: ALL=(ALL) NOPASSWD:ALL
          groups: mak3r, users, admin
        - name: root
          passwd: root
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHVZtKeG7C1CmMYh07Rgm6JkbIZ90DpjuKip1Aexhm5qz0O/E6w6tB0FTd2rCWO+FtOYpFMT2ao9dqeMvBTkTRGGQZ1nG+QaWYFGExS5lGUm+n9GXJU34LK6fcVx7xgZ3rw7RKWYXPmS/hIujSKRL0Qj9RMuVHIVMzDUzUL9zYOEHyLtY5OkHgzCp8wcVyx7CdBY/G3gru42MQmLoN3yJV1mti7YS9IjY99i55M5FeUe4/NcukHoYkMuyHtHugHlXeficAhpUrsouKRnMaXDFCK4sGmZucF8zpyXpG8qcGE+S6b5e/NderR+HlWTbpURiFJRthwCr2pAR90pvanuUN markabrams@marks-mbp.lan
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDoEYEqeNoGwGGmduMtGbt/CieztNdtXXFt+8eckYGgmktnjKgu2gwKUsi63jmTblRKgpmTp8iigDjZV23M6XhZOxvCU+PyhsxLeg3hsAaWNjzwKzGjxl8026A9ssPwf3H5YLyjzWPn1OTx7ej52uNQW5XpGNBjUYgMLuhjPMeNE/8ajQaz03COYsVlrYji5uH7axJGeEOS4j9+B9TP2j4YVwsKgHVyh6h94RArkBMDIZadw3ZMmi1t0nOXgcemWdTP6BvJQQEvdrg5w6LskUClxlETPdKkQGI3V0IG+A0ywFjO9aA7AmPLZlN/upgMaLRtxnUl2J/VT2olGtL/dedv2AmpAcDXW4u1mFGvjZj8+FX29U/ineeBDEWXaou/KwpCtZ9NPJdZwl1IW+hFj7R4lxQx2viUMu1Nfe4xL+NvFPMcCVSMCBfvNCWAToBXmhiSg8TJiYIqvV4xHl7vokNP5Cb+Y8Ap4K+IdYGyW2r7VEf783R/c1Co3eDC3lA9x0E= mak3r@devnuc
      ssh_import_id:
        - gh:mak3r
      write_files:
      - content: |
          # /etc/udev/rules.d/11-ftdi.rules

          # FT232H
          SUBSYSTEM=="usb", ATTR{idVendor}=="0403", ATTR{idProduct}=="6014", GROUP="plugdev", MODE="0664"
        path: /etc/udev/rules.d/11-ftdi.rules
        permissions: "0644"
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
        eject-cd: true
      registration:
        emulate-tpm: true
        emulated-tpm-seed: -1
  machineName: "${System Information/UUID}"
  machineInventoryLabels:
    location: "us"
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
