apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: nuc-teal-demo
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: mak3r
          sudo: ALL=(ALL) NOPASSWD:ALL
          groups: mak3r, users, admin
        - name: root
          passwd: root
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/4vVlIbPrvtlZfnOHja8XVjZuVldojJQIz+/ms8PFifdmKqcFaoKNQnTJJ1uERcUkhruNMi9gk9R+bpjZZHfI0pcfWc+qWTaXMGmvGmuJRnryUMgUTW+uUAdRp5lgnybyh6XYXz3DIVElwzelRbuuhSTstyCHZDaO5NjirkeMUiL58S4DQZguyRuSIeT6L8j+uMuvrZSc2c4b/bMJ+nmhpHQNdTd5aZFpyXRIjSGBMGTXNTeKgVkbKqkf2hLNmo7gjAHd6zwM/1xJWFSqA5Jo5LDhl/gyy369oTZ7dhA/CzaStwE+BRu+yz/w/Qrm1mbXYDOb2zYSVRVWrgVPTBblPc0yybGM0OO+qQw8NQU+nWUFOs059kckWC/P3kGvW/wtfNQ3S+IvV3+HzTaVWW8tk7Hj3h4D7KFZDgRNYGYK3DnYjBJHnR/CC+eL2niC2NS66uB75aBnfLiAXvEV4cx6KqJ9DcVTVGOYKWgkX/MheMxwhM//pzQgzhBMzzxTsc0= suse-mak3r@zephyrus
      write_files:
      - encoding: b64
        content: W2Nvbm5lY3Rpb25dCmlkPWdsaW5ldAp0eXBlPXdpZmkKaW50ZXJmYWNlLW5hbWU9d2xhbjAKcGVybWlzc2lvbnM9CnRpbWVzdGFtcD0xNjcxNTQ5NjQxCgpbd2lmaV0KbWFjLWFkZHJlc3MtYmxhY2tsaXN0PQptb2RlPWluZnJhc3RydWN0dXJlCnNzaWQ9U1VTRUNPTgoKW3dpZmktc2VjdXJpdHldCmtleS1tZ210PXdwYS1wc2sKcHNrPUlubm92YXRlCgpbaXB2NF0KZG5zLXNlYXJjaD0KbWV0aG9kPWF1dG8KCltpcHY2XQphZGRyLWdlbi1tb2RlPXN0YWJsZS1wcml2YWN5CmRucy1zZWFyY2g9Cm1ldGhvZD1hdXRv
        path: /etc/NetworkManager/system-connections/susecon2023.connection
      - content: |
          # /etc/udev/rules.d/90-kbd-mini.rules

          # Keyboard Mini
          SUBSYSTEM=="usb", KERNEL=="usb[0-9]*", ATTR{product}=="mini keyboard"
        path: /etc/udev/rules.d/90-kbd-mini.rules
        permissions: "0644"
    elemental:
      install:
        poweroff: true
        device: /dev/nvme0n1
        debug: true
  machineName: "mak3r-${System Information/UUID}"
  machineInventoryLabels:
    location: "de"
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
