apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: kvm-demo
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: mak3r
          sudo: ALL=(ALL) NOPASSWD:ALL
          groups: mak3r, users, admin
        - name: root
          passwd: root
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHVZtKeG7C1CmMYh07Rgm6JkbIZ90DpjuKip1Aexhm5qz0O/E6w6tB0FTd2rCWO+FtOYpFMT2ao9dqeMvBTkTRGGQZ1nG+QaWYFGExS5lGUm+n9GXJU34LK6fcVx7xgZ3rw7RKWYXPmS/hIujSKRL0Qj9RMuVHIVMzDUzUL9zYOEHyLtY5OkHgzCp8wcVyx7CdBY/G3gru42MQmLoN3yJV1mti7YS9IjY99i55M5FeUe4/NcukHoYkMuyHtHugHlXeficAhpUrsouKRnMaXDFCK4sGmZucF8zpyXpG8qcGE+S6b5e/NderR+HlWTbpURiFJRthwCr2pAR90pvanuUN markabrams@marks-mbp.lan
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC/4vVlIbPrvtlZfnOHja8XVjZuVldojJQIz+/ms8PFifdmKqcFaoKNQnTJJ1uERcUkhruNMi9gk9R+bpjZZHfI0pcfWc+qWTaXMGmvGmuJRnryUMgUTW+uUAdRp5lgnybyh6XYXz3DIVElwzelRbuuhSTstyCHZDaO5NjirkeMUiL58S4DQZguyRuSIeT6L8j+uMuvrZSc2c4b/bMJ+nmhpHQNdTd5aZFpyXRIjSGBMGTXNTeKgVkbKqkf2hLNmo7gjAHd6zwM/1xJWFSqA5Jo5LDhl/gyy369oTZ7dhA/CzaStwE+BRu+yz/w/Qrm1mbXYDOb2zYSVRVWrgVPTBblPc0yybGM0OO+qQw8NQU+nWUFOs059kckWC/P3kGvW/wtfNQ3S+IvV3+HzTaVWW8tk7Hj3h4D7KFZDgRNYGYK3DnYjBJHnR/CC+eL2niC2NS66uB75aBnfLiAXvEV4cx6KqJ9DcVTVGOYKWgkX/MheMxwhM//pzQgzhBMzzxTsc0= suse-mak3r@zephyrus
      ssh_import_id:
        - gh:mak3r
      write_files:
      - content: |
          # /etc/udev/rules.d/11-ftdi.rules

          # FT232H
          SUBSYSTEM=="usb", ATTR{idVendor}=="0403", ATTR{idProduct}=="6014", GROUP="plugdev", MODE="0664"
        path: /etc/udev/rules.d/11-ftdi.rules
        permissions: "0644"
    elemental:
      install:
        reboot: true
        device: /dev/vda
        debug: true
        eject-cd: true
      registration:
        emulate-tpm: true
        emulated-tpm-seed: -1
  machineName: "${System Information/UUID}"
  machineInventoryLabels:
    location: "us"
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
